Repository gits-up/temp-conversion, pull requests merged in 2023-10, with the labels that each got.

#2 Major redesign and added couple more temperature converters
  README.md
  index.html
  script.js
  tempConversion.js
Labels: HACKOCTOBERFEST

#6 Made some UI changes
  styles.css
Labels: HACKOCTOBERFEST

#7 Updated Readme.md file(Issue no. #3)
  README.md
  images/Hacktoberfestlogo.jpg
  images/ProjectOverview.png
Labels: HACKOCTOBERFEST, hackoctoberfest-accepted

#13 doc: update JSDoc for tempConversion.js
  tempConversion.js
Labels: HACKOCTOBERFEST, hackoctoberfest-accepted

#11 added FEATURE : Dark Mode
  index.html
  script.js
  styles.css
Labels: HACKOCTOBERFEST, hackoctoberfest-accepted

#17 Changes in UI
  index.html
  styles.css
Labels: HACKOCTOBERFEST, hackoctoberfest-accepted

#22 Fixed: DARK MODE BUG - changed the color white to purple in light mode…
  script.js
Labels: HACKOCTOBERFEST, hackoctoberfest-accepted, hacktoberfest, hacktoberfest-accepted

#23 Add ability to optionally use the enter key to convert temperature
  script.js
Labels: HACKOCTOBERFEST, hackoctoberfest-accepted, hacktoberfest, hacktoberfest-accepted

#25 Fix:issue:24
  styles.css
Labels: HACKOCTOBERFEST, hackoctoberfest-accepted, hacktoberfest, hacktoberfest-accepted

#31 Update index.html
  index.html
Labels: HACKOCTOBERFEST, hackoctoberfest-accepted, hacktoberfest, hacktoberfest-accepted
